name: Build

on:
  workflow_call:
    ref:
      description: 'The git ref to build'
      required: true
      type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.name-artifact.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run build
      - id: name-artifact
        run: echo "::set-output name=artifact-name::website-${{ github.sha }}"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.name-artifact.outputs.artifact-name }}
          path: out/
