name: Deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The artifact to deploy'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}

      - name: Extract tar archive
        run: tar -xvfz out.tar.gz

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=out/
        env:
          NETLIFY_SITE_ID: e464072b-c4e2-4ca9-b6d5-317fd657ad16
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
