on:
  push:
    branches:
      - master

jobs:
  build:
    uses: underyx/visawhen/.github/workflows/build.yml@main
    with:
      ref: ${{ github.sha }}

  deploy:
    uses: underyx/visawhen/.github/workflows/deploy.yml@main
    needs: [build]
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
