name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    uses: underyx/visawhen/.github/workflows/semgrep.yml@main
    secrets:
      semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
    with:
      continue-on-error: true

  pre-commit:
    uses: underyx/visawhen/.github/workflows/pre-commit.yml@main

  build:
    uses: underyx/visawhen/.github/workflows/build.yml@main
    with:
      ref: ${{ github.sha }}

  deploy:
    uses: underyx/visawhen/.github/workflows/deploy.yml@main
    needs: [build]
    secrets:
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
