name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    uses: underyx/visawhen/.github/workflows/semgrep.yml@main

  build:
    uses: underyx/visawhen/.github/workflows/build.yml@main
    with:
      ref: ${{ github.sha }}

  deploy:
    uses: underyx/visawhen/.github/workflows/deploy.yml@main
    needs: [build]
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
