on:
  workflow_call:
    secrets:
      semgrep-app-token:
        required: true
name: Semgrep
jobs:
  semgrep:
    name: Scan with Semgrep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.semgrep-app-token }}
